// Imports
import type { Metadata } from 'next'

// Fonts
import { Kumbh_Sans } from 'next/font/google'
const kumbh_sans = Kumbh_Sans({ subsets: ['latin'] })

// Style
import './globals.css'

// Seo
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Root
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={kumbh_sans.className}>{children}</body>
    </html>
  )
}
